config-map:
  platform-external-e2e-run.sh: |
    # CHANGEME: Placeholder for running external e2e tests

    # Results must be saved on the ${RESULTS_DIR}
    pushd "${RESULTS_DIR}" || true
    
    # CHANGEME: copy files to this directory
    echo "test e2e" > test-result.txt
    
    popd

podSpec:
  restartPolicy: Never
  serviceAccountName: sonobuoy-serviceaccount
  volumes:
    - name: shared
      emptyDir: {}
  containers:
    - name: report-progress
      image: "{{ .PluginsImage }}"
      imagePullPolicy: Always
      priorityClassName: system-node-critical
      command: ["./report-progress.sh"]
      volumeMounts:
      - mountPath: /tmp/sonobuoy/results
        name: results
      - mountPath: /tmp/shared
        name: shared
      env:
        - name: PLUGIN_ID
          value: "30"
        - name: ENV_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ENV_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ENV_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
sonobuoy-config:
  driver: Job
  plugin-name: 30-openshift-conformance-external
  result-format: raw
  description: The end-to-end tests maintained by OpenShift to validate the Provider running the OpenShift Container Platform.
  source-url: https://github.com/redhat-openshift-ecosystem/provider-certification-tool/blob/main/manifests/openshift-conformance-external.yaml
  skipCleanup: true
spec:
  name: plugin
  image: "{{ .PluginsImage }}"
  imagePullPolicy: Always
  priorityClassName: system-node-critical
  volumeMounts:
  - mountPath: /tmp/sonobuoy/results
    name: results
  - mountPath: /tmp/shared
    name: shared
  env:
    - name: PLUGIN_ID
      value: "30"
    - name: ENV_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: ENV_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: ENV_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: RUN_MODE
      valueFrom:
        configMapKeyRef:
          name: plugins-config
          key: run-mode
    - name: DEV_MODE_COUNT
      valueFrom:
        configMapKeyRef:
          name: plugins-config
          key: dev-count
    - name: MIRROR_IMAGE_REPOSITORY
      valueFrom:
        configMapKeyRef:
          name: plugins-config
          key: mirror-registry
          optional: true
