---
- name: OPCT | Run | Init Vars
  ansible.builtin.import_playbook: opct-init-vars.yaml

- name: OPCT | Run | Preflight
  ansible.builtin.import_playbook: opct-run-tool-preflight.yaml
  when: not(skip_prefligth | d(false))

- name: OPCT | Run | Task runner
  hosts: localhost
  gather_facts: yes
  vars:
    opct_bin: /openshift-provider-cert
    # OPCT runs in average of 2.5h, the timeout is set to 4h
    # pooling the status of the task every 60 seconds.
    opct_task_timeout_sec: 14400
    opct_task_check_delay_sec: 60
    opct_task_check_retries: 241
    opct_plugins_result: []

  tasks:
  - name: OPCT | Run | Set results path
    ansible.builtin.set_fact:
      results_path: "{{ cluster_path }}/opct"
    when: results_path is not defined

  - name: OPCT | Run | Set log_pipe
    ansible.builtin.set_fact:
      log_pipe: "{{ results_path }}/opct-runner.log"
    when: log_pipe is not defined

  - name: OPCT | Run | Set play_start_time
    ansible.builtin.set_fact:
      play_start: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

  - name: OPCT | Run | Assert results path exists
    ansible.builtin.file:
      state: directory
      path: "{{ results_path }}"

  # Schedule async task to run OPCT
  # The OPCT will run in watcher mode (-w), once it finished,
  # the artifacts will be collected.
  - name: OPCT | Run | Run Async task
    async: "{{ opct_task_timeout_sec }}"
    poll: 0
    args:
      chdir: "{{ results_path }}"
    environment:
      KUBECONFIG: "{{ kubeconfig }}"
    # Python env should be explicit set, otherwise the VENV will
    # raise the error described in this issue: 
    # https://github.com/ansible/ansible/issues/43286#issuecomment-489981184
    vars:
      ansible_python_interpreter: /usr/bin/env python3
    ansible.builtin.shell: |
      echo "> INIT OPCT task runner [{{ ansible_date_time.iso8601 }}]" | tee -a {{ log_pipe }};
      echo ">> Dump vars" | tee -a {{ log_pipe }};
      echo "opct path=[{{ opct_bin }}] version:" | tee -a {{ log_pipe }};
      {{ opct_bin }} version

      echo "> Starting task:" | tee -a {{ log_pipe }};
      {{ opct_bin }} run -w {{ opct_run_mode | d('') }} {{ opct_run_args | d('') }} 2>&1 | tee -a {{ log_pipe }};

      echo "> Retrieve results:"
      {{ opct_bin }} retrieve 2>&1 | tee -a {{ log_pipe }};
    register: opct_run

  - name: OPCT | Run | Task Summary
    ansible.builtin.debug:
      msg:
        - "Result path is set to directory {{ results_path }}"
        - "Async Task scheduled with ID {{ opct_run.ansible_job_id }}"
        - "Task timeout is {{ opct_task_timeout_sec  }} seconds."
        - "Task status will check every {{ opct_task_check_delay_sec  }} seconds for {{ opct_task_check_retries }} times."
        - "Task status will return 'FAILED - RETRYING' while OPCT is running"
        - "Task stdout/err is available on the log file {{ log_pipe }}"
        - "Check the execution: 'tail -f {{ log_pipe }}'"
        - "Check the environment: 'oc --kubeconfig {{ kubeconfig }} get pods -n openshift-provider-certification'"
        - "OPCT run cmd: {{ opct_bin }} run -w {{ opct_run_mode | d('') }} {{ opct_run_args | d('') }} 2>&1 | tee -a {{ log_pipe }};"
        - "OPCT retrieve cmd: {{ opct_bin }} retrieve  2>&1 | tee -a {{ log_pipe }}"

  - name: OPCT | Run | Check async task every 60 sec
    ansible.builtin.async_status:
      jid: "{{ opct_run.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 240 # 4h
    delay: 60
    vars:
      ansible_python_interpreter: /usr/bin/env python3

  - name: OPCT | Run | Debug opct_run
    ansible.builtin.debug:
      var: opct_run

  - name: OPCT | Run | Show stdout
    ansible.builtin.debug:
      var: job_result.stdout_lines
    when: job_result.stderr_lines | length == 0

  - name: OPCT | Run | Show stderr
    ansible.builtin.debug:
      var: job_result.stderr_lines
    when: job_result.stderr_lines | length > 0

  # TODO: this parser should be replaced with a built-in report on OPCT
  # https://issues.redhat.com/browse/OPCT-9
  - name: OPCT | Run | Collecting Plugin results
    args:
      chdir: "{{ results_path }}"
    ansible.builtin.shell: |
      {{ opct_bin }} results -p {{ item.plugin_name }} ./*.tar.gz 2>&1 \
        | grep ^Plugin -A 5 \
        | sed -e 's/: /=/g' \
        | sed ':a;N;$!ba;s/\n/ /g' \
        | tee -a {{ log_pipe }};
    when: job_result.stderr_lines | length == 0
    with_items:
    - plugin_name: 05-openshift-cluster-upgrade
    - plugin_name: 10-openshift-kube-conformance
    - plugin_name: 20-openshift-conformance-validated
    register: res_plugins

  - name: OPCT | Run | Aggregate the results
    ansible.builtin.set_fact:
      opct_plugins_result: "{{ opct_plugins_result + [item.stdout] }}"
    with_items: "{{ res_plugins.results }}"

  - name: OPCT | Run | Get timestamp from the system
    shell: "date +'%Y-%m-%d %H:%M:%S'"
    register: tstamp
    changed_when: false

  - name: OPCT | Run | Set play_end_time
    ansible.builtin.set_fact:
      play_end: "{{ tstamp.stdout }}"

  - name: OPCT | Run | Overview
    ansible.builtin.debug:
      msg:
        - "Job attempts={{ job_result.stderr_lines }}"
        - "Job time delta={{ job_result.delta }} start={{ job_result.start }} end={{ job_result.start }}"
        - "Job attempts={{ job_result.attempts }}"
        - "Execution time: {{ ((play_end | to_datetime) - (play_start | to_datetime)) }}"
        - "Plugins Results: {{ opct_plugins_result }}"

  # TODO
  # - save artifacts somewhere
