---
- name: Setup OPCT Cluster Tests - Create Paused MCP
  hosts: localhost
  tasks:
  - name: Create Paused MCP
    environment:
      KUBECONFIG: "{{ kubeconfig }}"
    kubernetes.core.k8s:
      state: present
      api_version: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      name: opct
      definition:
        spec:
          machineConfigSelector:
            matchExpressions:
            - key: machineconfiguration.openshift.io/role,
              operator: In,
              values: [worker,opct]
          nodeSelector:
            matchLabels:
              "node-role.kubernetes.io/tests": ''
          paused: true
