---
# ansible-playbook opct-install-cluster.yaml \
#  -e cluster_name=demo \
#  -e cluster_version=4.12.0-rc.4

- name: OPCT | Cluster Create | AWS | Check Args
  hosts: opct_aws
  tasks:
  - name: OPCT | Cluster Create | AWS | Check  cluster_name
    ansible.builtin.assert:
      that:
        - cluster_name is defined
      fail_msg: "'cluster_name' is not defined. Set the '-e cluster_name=value' "

  - name: OPCT | Cluster Create | AWS | Check cluster_version
    ansible.builtin.assert:
      that:
        - cluster_version is defined
      fail_msg: "'cluster_version' is not defined. Set the '-e cluster_version=4.11.18' "


- name: OPCT | Cluster Create | AWS
  hosts: '{{ target|default("localhost") }}'
  connection: local
  gather_facts: true

  vars:
    # used on installer clients
    release_image: quay.io/openshift/okd
    release_version: "4.12.0-0.okd-2023-01-21-055900"
    skip_checks: yes
    # general usage
    okd_installer_env:
      CLUSTER_NAME: "{{ cluster_name }}"
      CLUSTER_VERSION: "{{ cluster_version }}"
      #CLUSTER_VERSION: "4.12.0-0.okd-scos-2023-01-17-234959"
      CONFIG_CLUSTER_NAME: "{{ cluster_name }}"
      CONFIG_PROVIDER: "{{ provider }}"
      CONFIG_CLUSTER_REGION: "{{ provider_region }}"
      CONFIG_PLATFORM: "{{ config_platform }}"
      CONFIG_BASE_DOMAIN: "{{ config_base_domain }}"
      #CONFIG_PULL_SECRET_FILE:  "{{ ansible_env.HOME }}/{{ config_pull_secret_home }}"
      CONFIG_SSH_KEY: "{{ lookup('file', ansible_env.HOME + '/' + config_ssh_key_home) }}"

  pre_tasks:
  - name: OPCT | Cluster Create | AWS | Set Installer Env vars
    set_fact:
      okd_installer_env: "{{ okd_installer_env }}"

- name: OPCT | Cluster Create | AWS | Check clients are installed
  ansible.builtin.import_playbook: mtulio.okd_installer.install_clients
  vars:
    release_image: quay.io/openshift/okd
    release_version: "4.12.0-0.okd-2023-01-21-055900"
    skip_checks: yes

- name: OPCT | Cluster Create | AWS | Generate the install-config
  ansible.builtin.import_playbook: mtulio.okd_installer.config
  vars:
    mode: "create"
    cluster_name: "{{ okd_installer_env.CONFIG_CLUSTER_NAME }}"
  environment: "{{ okd_installer_env }}"

- name: OPCT | Cluster Create | AWS | Create all stacks
  ansible.builtin.import_playbook: mtulio.okd_installer.create_all
  vars:
    target: opct_aws
  environment: "{{ okd_installer_env }}"

- name: OPCT | Cluster Create | AWS | Finish
  hosts: '{{ target|default("localhost") }}'
  connection: local
  gather_facts: true

  tasks:
    - name: OPCT | Cluster Create | AWS | Overview
      ansible.builtin.debug:
        msg:
          - "export KUBECONFIG={{ ansible_env.HOME }}/.ansible/okd-installer/clusters/{{ cluster_name }}/auth/kubeconfig"
