---
- name: OPCT Runner ALL AWS | Set Timer
  hosts: localhost
  gather_facts: yes
  tasks:
  - name: OPCT | Runner All AWS | Set Timer start
    ansible.builtin.set_fact:
      opct_rall_t_start: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

- name: OPCT | Runner All AWS | Cluster create
  ansible.builtin.import_playbook: opct-cluster-create-aws.yaml

- name: OPCT Runner ALL AWS | Set Timer
  hosts: localhost
  gather_facts: yes
  tasks:
  - name: OPCT | Runner All AWS | Set Timer createend
    ansible.builtin.set_fact:
      opct_rall_t_createend: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

- name: OPCT | Runner All AWS | Run tool
  ansible.builtin.import_playbook: opct-run-tool.yaml
  when: not(skip_run | d(false))

- name: OPCT Runner ALL AWS | Set Timer
  hosts: localhost
  gather_facts: yes
  tasks:
  - name: OPCT | Runner All AWS | Set Timer runend
    ansible.builtin.set_fact:
      opct_rall_t_runend: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

- name: OPCT | Runner All AWS | Cluster delete
  ansible.builtin.import_playbook: opct-cluster-delete-aws.yaml 
  when: not(skip_delete | d(false))

- name: OPCT Runner ALL AWS | Finish
  hosts: localhost
  gather_facts: yes
  tasks:
  - name: OPCT | Runner All AWS | Set Timer end
    ansible.builtin.set_fact:
      opct_rall_t_end: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

  - name: OPCT | Runner All AWS | Overview
    ansible.builtin.debug:
      msg:
        - "Execution time: {{ ((opct_rall_t_end | to_datetime) - (opct_rall_t_start | to_datetime)) }}"
        - "Create Cluster time: {{ ((opct_rall_t_createend | to_datetime) - (opct_rall_t_start | to_datetime)) }}"
        - "Run tool time: {{ ((opct_rall_t_runend | to_datetime) - (opct_rall_t_createend | to_datetime)) }}"
        - "Destroy cluster time: {{ ((opct_rall_t_end | to_datetime) - (opct_rall_t_runend | to_datetime)) }}"
