---
- name: Setup OPCT Cluster Tests - Enable Local Image Registry
  hosts: localhost
  tasks:
  - name: Create Manage Image Registry emptyDir
    environment:
      KUBECONFIG: "{{ kubeconfig }}"
    register: create_registry
    until: "create_registry is not failed"
    retries: 5
    delay: 5
    kubernetes.core.k8s:
      state: present
      api_version: imageregistry.operator.openshift.io/v1
      kind: Config
      name: cluster
      definition:
        spec:
          managementState: Managed
          storage:
            emptyDir: {}
