---
- name: OPCT | Init Vars
  hosts: localhost
  gather_facts: yes

  vars:
    installer_path: "{{ ansible_env.HOME + '/.ansible/okd-installer' }}"

  tasks:
  - name: OPCT | Init Vars | cluster_path
    ansible.builtin.set_fact:
      cluster_path: "{{ installer_path }}/clusters/{{ cluster_name }}"

  - name: OPCT | Init Vars | oc_bin, kubeconfig
    ansible.builtin.set_fact:
      oc_bin: "{{ installer_path }}/bin/oc"
      kubeconfig: "{{ cluster_path }}/auth/kubeconfig"
